{
 "title": "CBTT",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Read Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "\n\navg(\n    rate(\n      container_fs_reads_bytes_total{namespace=\"cbtt\",pod=~\"^cbtt-test-.*\"}[5h])\n) by (pod)*3600*5",
     "legendFormat": "{{pod_set}}"
    }
   ]
  },
  {
   "title": "Written Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "\n\navg(\n    rate(\n      container_fs_writes_bytes_total{namespace=\"cbtt\",pod=~\"^cbtt-test-.*\"}[5h])\n) by (pod)*3600*5",
     "legendFormat": "{{pod_set}}"
    }
   ]
  },
  {
   "title": "Received Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(\n    rate(\n      container_network_receive_bytes_total{namespace=\"cbtt\",pod=~\"^cbtt-test-.*\"}\n      [10h])\n) by (pod)*3600*10\n",
     "legendFormat": "{{pod_set}}"
    }
   ]
  },
  {
   "title": "Transmit Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(\n    rate(\n      container_network_transmit_bytes_total{namespace=\"cbtt\",pod=~\"^cbtt-test-.*\"}\n      [10h])\n) by (pod)*3600*10\n",
     "legendFormat": "{{pod_set}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(\n    avg_over_time(container_memory_working_set_bytes{namespace=\"cbtt\",pod=~\"^cbtt-test-.*\"}[10h])\n) by (pod)",
     "legendFormat": "{{pod_set}}"
    }
   ]
  },
  {
   "title": "CPU usage (s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(\n    rate(\n      container_cpu_usage_seconds_total{namespace=\"cbtt\",pod=~\"^cbtt-test-.*\"}[10h])\n) by (pod)*3600*10",
     "legendFormat": "{{pod_set}}"
    }
   ]
  },
  {
   "title": "Time (s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg(\n      kube_pod_completion_time{namespace=\"cbtt\",pod=~\"^cbtt-test-.*\"} - kube_pod_start_time{namespace=\"cbtt\",pod=~\"^cbtt-test-.*\"}\n) by (pod)\n",
     "legendFormat": "{{pod_set}}"
    }
   ]
  }
 ]
}