apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-server
data:
  REGISTRY_URL: {{ .Values.registry.url | b64enc | quote }}
  REGISTRY_PREFIX: {{ .Values.registry.prefix | b64enc | quote }}
  REGISTRY_USERNAME: {{ .Values.registry.username | b64enc | quote }}
  REGISTRY_PASSWORD: {{ .Values.registry.password | b64enc | quote }}
  USERNAME: {{ .Values.client.username | b64enc | quote }}
  PASSWORD: {{ .Values.client.password | b64enc | quote }}