apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-client
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-server
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: {{ .Release.Name }}
